# Generated by Django 4.2.1 on 2023-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_play_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Board/Card Game', 'Board/Card Game'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(),
        ),
    ]
