# Generated by Django 4.2.1 on 2023-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_play_app', '0002_alter_game_category_alter_game_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(),
        ),
    ]
