# Generated by Django 4.2 on 2023-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepe',
            name='image_url',
            field=models.URLField(),
        ),
    ]
